package ru.begletsov.video_courses.udemy.JAVA_get_black_belt._8_thread._11_lock_reentrantlock._11_bankomat_example;

import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;

public class _11_Bankomat {
    public static void main(String[] args) throws InterruptedException {
        Lock lock = new ReentrantLock();
        new Employee("Zaur", lock);
        new Employee("Oleg", lock);
        new Employee("Lena", lock);
        Thread.sleep(5000);
        new Employee("Viktor", lock);
        new Employee("Marina", lock);

        //console (lock-unlock):
        //Marina ждет...
        //Lena ждет...
        //Oleg ждет...
        //Viktor ждет...
        //Marina пользуется банкоматом...
        //Zaur ждет...
        //Marina заершил пользование банкоматом...
        //Oleg пользуется банкоматом...
        //Oleg заершил пользование банкоматом...
        //Viktor пользуется банкоматом...
        //Viktor заершил пользование банкоматом...
        //Zaur пользуется банкоматом...
        //Zaur заершил пользование банкоматом...
        //Lena пользуется банкоматом...
        //Lena заершил пользование банкоматом...

        //console (trylock):
        //Lena не хочет ждать в очереди
        //Oleg не хочет ждать в очереди
        //Zaur пользуется банкоматом...
        //Zaur заершил пользование банкоматом...
        //Viktor пользуется банкоматом...
        //Marina не хочет ждать в очереди
        //Viktor заершил пользование банкоматом...
    }
}
